apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tax-tracker-ingress
  namespace: tax-tracker
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: tracker.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tax-tracker
                port:
                  number: 8085
  tls:
    - hosts:
        - tracker.home
      secretName: tracker-tls
